### ISSUE TITLE
now its really a issue 

### ISSUE THREAD

**Issue by ghost** [nihilowy/surfer#10]
so yeah
i was using discord on surfer
but when i clicked in the gif icon and the tenor thing loaded
the cpu usage went crazy, the fan started spinning super fast and the entire system got slow
this doesn't happen in surf or epiphany
so something very serious is happening here
when surfer tries to load the tenor page with a bunch of gifs

**Comment by nihilowy** [comment]
tenor.com ? it works for me. I clicked on random gifs , saved it - nothing happens
Of course there can be issues i dont know .

btw this adblock  - wyebadblock works nice better than /etc/hosts

**Comment by nihilowy** [comment]
ok it was (this crashes / cpu hogs) probably web-gl . I disabled it. hope now is ok

**Comment by ghost** [comment]
nice, i'll be using more to see if find any problems
