### ISSUE TITLE
so, i got this idea last night, this might help you

### ISSUE THREAD

**Issue by ghost** [nihilowy/surfer#11]
see i don't know how easy it is to do because i'm not a programmer 
but here is my idea

instead of editing the main surfer.c file to add new features 
you could keep the surfer.c clean with only basic things

and for each feature you create a new small .c file

making it easier to maintain

and i saw this from the wine-tkg 
you could make the make file read a txt file from the surfer folder for example
and in this txt file the user can specify what features he want enabled and disabled during the compilation 

thing1 = on
thing2 = on
thing3 = off

this way the files will survive "git pull"
and also possible to change the PKGBUILD file to compile only what the user wants from the browser

so in the future you can work more in the small .c file to fix or enhance any feature
instead of having to edit the main surfer .c

and i think the idea of being able to disable something in the browser could be a feature of surfer
like, if the user don't like something he can just disable it from the compilation

**Comment by nihilowy** [comment]
Thank You. 
I also dont consider myself programmer. I belive this will be easy to maintain - in reality its rather clone of surf with some new features /changes .Until webkit and gtk api make it possible to work
it will work . I will never plan doing real gtk / gnome app like epiphany or midori with building gobject classes ... and then dividing code on files make sense (look on epiphany code).

**Comment by nihilowy** [comment]
on chosing things to compile - it doesnt work here , because  it is too small.
If in example I compilled webkit (once) then I could chose something to disable - like wpebackend ( for mobile devices,) or x11 support.

**Comment by ghost** [comment]
i mean
the make file reads the txt file
and enables flags inside surfer.c
and surfer.c imports the code from the other .c files
like classes in java
surfer.c being the main file
and each feature having its own separate code
