### ISSUE TITLE
some updates

### ISSUE THREAD

**Issue by ghost** [nihilowy/surfer#12]
the browser is working great
still feels some stuttering over time
maybe the problem wasn't web-gl?

things that would be great are
notifications

be able to copy and paste images
right now "copy image" and "copy image address" do just the same thing
and its not possible to paste images
i have to drag from the file manager to the window
if i try to open the file manager to find a image i can't see the preview
so dragging the file is the best way right now

change black.css to style.css ( would make more sense )
and change " ctrl + / " to " ctrl + \ " ( they are near each other)

have a better way to show  the loading progress
if the window is maximized, make the browser show a line with the text of the percentage of the page loading, and it disappears when it reaches 100%
the user can click in the line to make it disappear or disable it in the surfer.c file

maybe last thing for the future
but you could implement a configuration file
instead of having to edit the surfer.c
the user could just edit a config file with the options he wants
and this would also help you to make the code cleaner

**Comment by nihilowy** [comment]
notice that stability of webkit on linux is still a issue.
Notifications from sites and copy paste images are not supported ( I think even on epiphany) 
keys - I try to stay it more intuitive  for user . But of course You can always customize it .
There are of course many things to add  but You know things are not so simple .
greets

**Comment by ghost** [comment]
i was testing, looks like html5 notifications work, so it will depend on the site
also its necessary to enable the notifications, so i think this might be all it needs
some way for the user to enable notifications for each site
maybe in the bookmarks, the user could change something in the html to enable the notifications?

about the keys
this is the US keyboard
![image](https://user-images.githubusercontent.com/20802412/83024333-c3eff480-a01d-11ea-9544-04452f2fe5d6.png)
and this is the BR keyboard
![image](https://user-images.githubusercontent.com/20802412/83024376-d36f3d80-a01d-11ea-9f38-6b6f75ff8c8e.png)

changing to \ would be a bad idea lol
