### ISSUE TITLE
Videos are broken

### ISSUE THREAD

**Issue by ghost** [nihilowy/surfer#13]
![Captura de tela de 2020-05-27 12-11-50](https://user-images.githubusercontent.com/20802412/83038712-cc9bf700-a02c-11ea-83ae-358bda16f9a0.png)
![Captura de tela de 2020-05-27 12-13-24](https://user-images.githubusercontent.com/20802412/83038717-cdcd2400-a02c-11ea-81e0-15f415d66ae5.png)
i had a similar problem with surf a long time ago

**Comment by nihilowy** [comment]
I dont know.  On arch linux I have these libs 
gst-libav 1.16.2-2
gst-plugins-bad-libs 1.16.2-11
gst-plugins-base 1.16.2-2
gst-plugins-base-libs 1.16.2-2
gst-plugins-good 1.16.2-3
gstreamer 1.16.2-2

and youtube works

**Comment by nihilowy** [comment]
I use mainly wayland sway (but it crashes when webkit does, then i simply restart sway )

**Comment by nihilowy** [comment]
btw in sway there are also some problems like deley in opening bars . In weston and gnome its working.
