### ISSUE TITLE
More Updates

### ISSUE THREAD

**Issue by ghost** [nihilowy/surfer#14]
i think you should close the other ones

ok , this time
the videos are still broken
but i can use mpv

~~i think you should change "(null)" to "surfer"
when i open surfer the title of the window is "(null)"
listing the bookmarks
if i open any page and hit "ctrl + h" i will go to the bookmarks page but the window will have no title
i think this might be easy to do by just changing the <title></title> in the html file~~

just add <title>something here</title> in the html file

also i'm learning **C**
so, maybe in 10 years i can help this project for real

**Comment by nihilowy** [comment]
good to hear. play with it, look on other projects wyeb vimb, lariza ,surf .but also real gtk apps. It is very pity that there are only a few books turtorial , mainly for beginers like  foundations of gtk+ development(you can download it). i think that free software ist so much popular, a that is the reason.
