### ISSUE TITLE
man asks more questions

### ISSUE THREAD

**Issue by ghost** [nihilowy/surfer#15]
i was thinking about using surfer for web development 
you think its possible to have live update on surfer?
to see the page changing while i edit it
and a option to save the file or files

maybe this is already possible and i just don't know how
i'm talking about using the web inspector

**Comment by nihilowy** [comment]
I dont  know .. 
 web inspector is baisicly for this https://www.youtube.com/watch?v=TuZJD-lKjCo

**Comment by ghost** [comment]
hmm, i would like to use the web inspector as a tool to develop webpages
also the videos are still not working
~~i don't know what i should do to make it work~~
i used this to compile and now the videos work
CC=/usr/bin/clang CFLAGS="-O3 -pipe -march=native -mtune=native" make

**Comment by nihilowy** [comment]
very interesting. What distro do you use ?

**Comment by ghost** [comment]
I use Arch btw

**Comment by ghost** [comment]
videos are broken again
i don't know what is going on

**Comment by nihilowy** [comment]
could you paste pacman -Q | grep gst ?

**Comment by ghost** [comment]
gst-libav 1.16.2-2
gst-plugins-bad 1.16.2-11
gst-plugins-bad-libs 1.16.2-11
gst-plugins-base 1.16.2-2
gst-plugins-base-libs 1.16.2-2
gst-plugins-good 1.16.2-3
gstreamer 1.16.2-2
gstreamer-vaapi 1.16.2-2

**Comment by nihilowy** [comment]
well seems ok . If dependecies are also instaled . To test gstreamer stand-alone You could download video by 
youtube-dl <uri> and then try
gst-play-1.0 -v that file
That must be something lack because I use it long time. You could also test in  sway or weston( I assume You use it in x11 )

**Comment by ghost** [comment]
the video works well with gsv
not i really don't know what is happening

**Comment by nihilowy** [comment]
if vidoes work in epiphany i am also confused.
