### ISSUE TITLE
literally using Issues as a chat

### ISSUE THREAD

**Issue by ghost** [nihilowy/surfer#18]
i've seen your new update
what is this private mode? how does it work?

also i was looking to test more wayland stuff and found this
https://github.com/natpen/awesome-wayland#Browser-without-X-library-dependency
look who is in the "Browser without X library dependency"
your browser is getting famous

**Comment by nihilowy** [comment]
hi,
priv mod - webkit epehemeral mode , it doesnt use cookies,not store cache or use it. It good for readng some newspapers like new comer:) it is in context/right click menu.
good to hear that someone see my project . at least until it exists :)

**Comment by ghost** [comment]
Found the perfect combination
Palemoon as my main browser and Surfer as my secondary browser
