### ISSUE TITLE
Icon

### ISSUE THREAD

**Issue by ghost** [nihilowy/surfer#20]
I made an icon In Blender 3D
see if you like
[Icons.zip](https://github.com/nihilowy/surfer/files/4975669/Icons.zip)

yeah 8x8 too lol
also close the other issues

or just use this one
and you do the resizing
![out](https://user-images.githubusercontent.com/20802412/88458908-a39ab580-ce67-11ea-8bc3-1611ddaca738.png)

**Comment by nihilowy** [comment]
oh You supprised me :)

seems like mac-like style.

now I must place it somewhere to /usr/share/icons . Mmaybe hicolors

You are real artist :)

**Comment by ghost** [comment]
imagine having a .desktop file and not having a icon
i just tried to make something like the webkit icon
its all i can do right now
i need to learn C to help more

**Comment by nihilowy** [comment]
Thats maybe because here on sway is iconless world /
but now they are biggest part of project ;)

**Comment by ghost** [comment]
I think you should only use 32x32 by now
and save the big one for the future
in case someone asks for a HiDPI icon
so you could just resize it

**Comment by nihilowy** [comment]
best woldbe svg icon . You think you can save in this format ?

**Comment by ghost** [comment]
not in blender
if so i will make a new one in...
this other program that makes svg images, i forgot the name

**Comment by nihilowy** [comment]
png dont look nice in gnome shell , they use scalable  svg  - /usr/share/icons/hicolor/scalable/aps/

**Comment by ghost** [comment]
>Gnome

**Comment by nihilowy** [comment]
it was link ?

**Comment by ghost** [comment]
wot?
the program? its inkscape
i just need to learn to use this thing
