### ISSUE TITLE
would be great if there was a site based  java script controller or umatrix extension support feature 

### ISSUE THREAD

**Issue by alansarkar** [nihilowy/surfer#21]
Really loving this browser Has a lot of useful features but would be great.  But would be epic  if it could support extensions too.

**Comment by nihilowy** [comment]
hi
support is only for wyebadblock .
js extension doesnt support custom sites(runs all).  both things are extensions releted and quite commplicated  - need be coded inside these extensions .

**Comment by nihilowy** [comment]
I added my  fixed version for ephy-scripts . look in directory.
