### ISSUE TITLE
poor video performance

### ISSUE THREAD

**Issue by John-Colvin** [nihilowy/surfer#22]
particularly 4k 60fps youtube barely works at all (perfectly smooth for me in other browsers, although epiphany seems unhappy about resizing videos while playing...)

**Comment by John-Colvin** [comment]
ok, so hardware acceleration was off, I set that to `blah_blah_ALWAYS` in `config.h`.

It still freezes up resizing videos, but that seems to happen with other webkitgtk browsers for me.

**Comment by nihilowy** [comment]
I defaulted it to never due to often crashes, it must be some deep problem ( or my gpu is too old)

**Comment by ghost** [comment]
@John-Colvin its a problem with gst
