### ISSUE TITLE
Remove some unnecessary options

### ISSUE THREAD

**Issue by ghost** [nihilowy/surfer#23]
i think its better to remove these

#define SURFER_TMPDOWNLOADS "/tmp"
#define SURFER_PLAYER	"mpv" 

for /tmp the browser already asks where to save the file
so its ok

and SURFER_PLAYER can easily be done with a simple script in dmenu

so you could do like that
instead of opening a link with mpv
you could change it to
"open link with"

and the user could decide what programs go into the list of "open link with"
like
mpv, vlc, audacious, mocp

**Comment by nihilowy** [comment]
hi
I use download to tmp , its nice for testing , also doesnt ask for locations:)

Open with scripts?  - maybe possible.  But why bother if it just works now ?

**Comment by ghost** [comment]
Surfer doesn't ask you where to save the file?

**Comment by nihilowy** [comment]
if I save to tmp it doesnt ask .

**Comment by ghost** [comment]
i guess its fine
but i had this idea
not sure if its possible
instead of only opening a video with mpv
the user be able to list the programs he wants
and surfer runs " Binary + link "

**Comment by nihilowy** [comment]
I affraid its bigger thing - recognizing mime types, then saving choices etc.

**Comment by ghost** [comment]
not the mime
the same way surfer runs mpv
but the user can change what will be run
right click surfer will show the options
instead of only "Open with mpv"

**Comment by nihilowy** [comment]
so done. but tested only with mpv .

**Comment by ghost** [comment]
god
how many scripts do you need to do the same in firefox :roll_eyes: 
well i think its good enough
recomend inte README to make a folder with simbolic links to the files instead of reading /bin
/bin some times takes really long to read and theres just too many files
having all you need in a folder is also good because you could run scripts too

also
its good to ask but, do you think this could be a security flaw?

**Comment by nihilowy** [comment]
of course -  better to make special dir for these scripts , symbolic links for binary. But if someone use it will get it on his own :)
Is it secure - ? so if you use absolute path there is no problem. Other things is question of these players /scripts security .

**Comment by ghost** [comment]
i'm blocking ads using DNS
same result as /etc/hosts
but i still get ads in surfer
what could be happening?

**Comment by nihilowy** [comment]
never tried this method . I use these hosts from someonewhocares.org, and also  this small www.youtube.com script for youtube .

**Comment by ghost** [comment]
as far as i know /etc/hosts isn't good like using a dns recursor
and very limited too
might be something wrong
not all ads work, only simpe ones
so the list might be incomplete

**Comment by nihilowy** [comment]
i dont use dns recursor ( I hear about it first time) . I use only  networkmanager from gnome 
I have feeling that You use some vpn and need dns service >

**Comment by ghost** [comment]
no, its just a dns recursor + the stuff from here https://www.mypdns.org/
very good to block stuff and fast too
