### ISSUE TITLE
Pull Request(s)?

### ISSUE THREAD

**Issue by christianbundy** [nihilowy/surfer#3]
Hey @nihilowy!

I've been working with your project and started a small personal fork, but I want to check in and see whether you'd accept any of my changes. Here's a small list of my changes:

- Remove extra whitespace
- `.gitignore`
- `Makefile`:
  - Removed commented-out code
  - Replace `$INSTALLDIR` with `$DESTDIR`
- `PKGBUILD`: install to `$pkgdir/opt`
- `surfer.c`:
  - Use consistent indentation
  - Replace Ctrl+O with Ctrl+L
  - Remove commented-out code
- `surfer.desktop`: Replace "Web" with "Surfer"
- README.md`:
  - Use pure Markdown, no HTML.
  - Capitalization, formatting, and serial comma.

You can also view my code at <https://github.com/christianbundy/surfer>. Please let me know whether you'd like any PRs, or whether I should continue just using my personal fork. Thanks for your work on this project!

**Comment by nihilowy** [comment]
Please send commits -  then I can approve it.  Let  me add two things:
0) webkit is still unstable 
1) I am not programmer, and I dont plan any/much development ,
bye
