### ISSUE TITLE
need some informations

### ISSUE THREAD

**Issue by ghost** [nihilowy/surfer#6]
can i change where the style sheet will be by just changing 
#define USER_STYLESHEET_FILENAME	"/usr/share/surfer/black.css" ?
or the program will always search in "/usr/share/surfer/black.css" ?

same for
#define WEB_EXTENSIONS_DIRECTORY 	"/usr/lib/surfer"

and i want to change where .fav and .hist are saved

hmm
also can you add a -h or --help option to show the keys configured in the browser?

aye your browser works very well
much batter than surf in my opinion 

but i can't use tabbed
you have any idea how to use surfer in tabbed?

editing again
surfer isn't using /etc/hosts for some reason
it works in other browsers but not in surfer

and .css files
can i only use one .css file?

i want to use one for ads
and other for colors , but i think i can just make one with everything i need

**Comment by nihilowy** [comment]
Hi
all #define are macros so can be changed . .fav .hist are hard coded , maybe I will make it customize one day... . Regarding css style , of course it is just for one file. Someone here asked for possibility of adding diffrent css for diffrent site , these things can be done ( probbably ) but needs some work, research and so on. this is ONLY small project, if you look for something bigger I recomend  firefox  . Webkit bigest best browser is afaik epiphany.

FOr me bigest problem is webkit unstabilty  espacially on media video, streaming sites/

If you look for more stability and want to stay minimal falkon is good choice ( but it is basing on chrome blink and qt window toolkit )

Regarding tab - yes it dosnt has tabbs. but in sway wayland compositor - You can run it 
in this mode . If you very want tabs - please try epiphany , firefox ,lariza   (also minimalistic )

Maybe one day i will try adding support for css  - but cant promise anything

bye

**Comment by nihilowy** [comment]
and /etc/hosts - yes it works because I block adds through it
