### ISSUE TITLE
asking more questions

### ISSUE THREAD

**Issue by ghost** [nihilowy/surfer#7]
yo thank you very much for the change to use .surfer
now i was thinking

its possible to make the style be always used?
i'm using this one to hide ads 
http://floppymoose.com/

works very well for surf and surfer
but having to enable it every time is annoying
so i ask  if you could add an option to always use the style

 change to something like
always use the file in ".surfer/style.css"

and hit Ctrl + Shift + s to disable it
would make more sense, if someone already have the file in the folder its because he wants to use it

**Comment by nihilowy** [comment]
ok I hope it helps.

**Comment by ghost** [comment]
woa, thank you very much for the change
but i noticed that surfer isn't using /etc/hosts at all
still has ads from sites like youtube and some other that the css file can't hide
i'm using the hosts file from stevenblack

**Comment by nihilowy** [comment]
hello
afar i know /etc/hosts is global, so it affects all traffic . browser or any apps cant bypass it.
maybe You forgot clean cache  , i do it quite regulary:

rm  -r .cache/surfer or just rm -r .cache
