### ISSUE TITLE
u up?

### ISSUE THREAD

**Issue by ghost** [nihilowy/surfer#8]
so yeah i wanted to ask for more stuff

first, if you could add an indicator in the name of the window of how much the page has loaded
like 
loading "[33%] GitHub - Mozilla Firefox"
and after loading  "GitHub - Mozilla Firefox" 
(firefox as example)

second, an option to disable or change the way the browser handles the cookies
#define SURFER_COOKIE_POLICY        WEBKIT_COOKIE_POLICY_ACCEPT_ALWAYS

to something like
always = accept all cookies
no third-party = do not accept third-party cookies and cookies from unvisited sites
disabled = do not accept cookies

3rst, i think this one might be really hard to add
but i ask if you could add an option to choose where the user want to save a file
instead of saving it to "downloads", i know its faster
but i think its better to be asked where i want to save the file
for example, i like to save some images in /tmp, because its just some meme that i want to send to someone, the image will be deleted when i restart my computer

just that
everything else in surfer is awesome, i'm loving it
keep the awesome work

**Comment by nihilowy** [comment]
I added progres indication, rest maybe in future
bye

**Comment by nihilowy** [comment]
I added new menu options 
- play uri in mpv  ( if supported by youtube-dl)
-tmp download

**Comment by ghost** [comment]
but how does that work? and what menu?

**Comment by nihilowy** [comment]
popup menu .  But You probbably have already noticed.

**Comment by Danilopereira82** [comment]
no i didn't
where is it?

**Comment by Danilopereira82** [comment]
oww
i see it now
it only works in some situations

**Comment by ghost** [comment]
i see now
the popup menu works only in some situations
about the "download to /tmp"
you don't need it
you just need to make the "save as" work well
because if i want to save a image for example
"save image" and "save as" do just the same thing
"save as" should let me decide where i want to save the file
